### ISSUE TITLE
Issue with event listener which loads plugin.

### ISSUE THREAD

**Issue by dil-bparihar** [Mati365/ckeditor5-rails#23]
# 🐛 Bug Report
Issue with event listener which loads plugin.
### 🔍 Bug Description
`<<~JS
        window.addEventListener('ckeditor:request-cjs-plugin:#{@plugin.name}', () => {
          window['#{@plugin.name}'] = #{code.html_safe};
        }, { once: true });
      JS`

On local all the plugin and patches loaded properly but in production for example in aws with ecs fargate it breaks and throws 504 gateway timeout. i think the way we are importing packages with async await is causing the issue. Which is taking time.

### ❌ Actual Behavior

A clear and concise description of what actually happened.

### 📋 Additional Context

- Add any other context about the problem here
- Include relevant logs if available
- List related issues/PRs

**Comment by Mati365** [comment]
@dil-bparihar It's most likely an infrastructure problem, as it's working properly in demos hosted on Hetzner. Like this one https://ckeditor5-rails.mati365.ovh/classic

**Comment by dil-bparihar** [comment]
@Mati365  Multiple script tags is being added for same event cjs event listener for plugin while using lazy loading tag. I can also see the same in your demo site too.

**Comment by Mati365** [comment]
@dil-bparihar without logs nothing I can do.

**Comment by dil-bparihar** [comment]
@Mati365 

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/6f246599-b80c-4fed-8d93-487247f17929" />

**Comment by Mati365** [comment]
@dil-bparihar It's not a cause of issue. Logs of the Rails server arę needed.

**Comment by Mati365** [comment]
Issue related to duplication of redundant inline plugins fixed in `1.27.3`.

**Comment by dil-bparihar** [comment]
It is very strange i have tried all possible ways to resolve it. But still issue persists. Application works perfectly fine with version: 1.24.10 . But when upgraded to version: 1.26.1 and above it start throwing error in production with 504. I cannot share you the logs because the request is not coming to the backed. Direct 504 gateway time out error after 1 minute. I tried increasing the idle timeout to 3 minutes but still its breaking. @Mati365

**Comment by dil-bparihar** [comment]
@Mati365  How can i remove the translation plugin just for testing purpose. I am not using it still i can see an empty hash window variable for it. 

`window.CKEDITOR_TRANSLATIONS`

https://github.com/Mati365/ckeditor5-rails/blob/c022d6591a1c65a40265c3daf29da8b4d27da571/lib/ckeditor5/rails/presets/preset_builder.rb#L359

**Comment by dil-bparihar** [comment]
@Mati365 ??

**Comment by Mati365** [comment]
@dil-bparihar 

```rb
plugins do 
   remove :CustomTranslationsLoader
end
```

**Comment by dil-bparihar** [comment]
But why this plugin is getting loaded every time on refresh page refresh as i am not using `custom_translations` method in ckeditor5.rb. Also 

```
plugins do 
   remove :CustomTranslationsLoader
end
```

is not working still it loads because i can see the window variable with empty hash.

<img width="267" alt="Image" src="https://github.com/user-attachments/assets/e99010fa-ac7e-4192-b7ec-115e04771433" />

And i think this is only causing because every time await import runs from the plugin code. @Mati365

**Comment by Mati365** [comment]
@dil-bparihar `window.CKEDITOR_TRANSLATIONS` is defined by CKEditor 5 CDN scripts.

> And i think this is only causing because every time await import runs from the plugin code. 

I don't think so, it's client-only thing.

**Comment by dil-bparihar** [comment]
In version 1.24.10 Pages does not break but it starts breaking when i upgrade it to version 1.26.1 or above @Mati365

**Comment by Mati365** [comment]
@dil-bparihar Please provide profiler or something that will help me debug which method is lagging. At this moment - dunno.

**Comment by Mati365** [comment]
@dil-bparihar Which particular version is affected? `1.25.0`?

**Comment by dil-bparihar** [comment]
version: 1.26.1

**Comment by Mati365** [comment]
@dil-bparihar `1.26.0` is affected?

**Comment by dil-bparihar** [comment]
I did not check it for 1.25.0 or 1.26.0 @Mati365

**Comment by Mati365** [comment]
@dil-bparihar Please check that, I don't know which particular change affect your server. Consider upgrading editor version.

**Comment by dil-bparihar** [comment]
```ruby
CKEditor5::Rails.configure do
  presets.define :custom do
    version '43.3.0'
    license_key ENV["CKEDITOR_LICENSE_KEY"]
    toolbar :sourceEditing, :|, :cut, :copy, :|, :undo, :redo, :|,
            :findAndReplace, :selectAll, :|, :bold, :italic, :underline, :strikethrough,
            :subscript, :superscript, :removeFormat, :|, :bulletedList, :numberedList,
            :outdent, :indent, :blockQuote, :|, :alignment, :link, :anchor, :|,
            :insertTable, :horizontalLine, :|, :fontFamily, :fontSize, :heading, :|, :fontColor, :fontBackgroundColor, should_group_when_full: false

    plugins :Essentials, :Paragraph, :Heading, :Bold, :Italic, :Underline, :Strikethrough,
            :Subscript, :Superscript, :RemoveFormat, :FindAndReplace, :SelectAll, :Alignment,
            :List, :Indent, :BlockQuote, :Link, :Table, :PlainTableOutput, :TableToolbar, :TableCaption, :TableProperties,
            :TableCellProperties, :HorizontalLine, :Font, :FontFamily, :FontSize,
            :FontColor, :FontBackgroundColor, :SourceEditing, :Indent, :IndentBlock
    translations :de, :en, :es, :fr, :it, :ja, :nl, :pt, :zh

    configure :fontFamily, {
      options: [
        'default',
        'Arial, Helvetica, sans-serif',
        'Calibri',
        'Comic Sans MS, cursive, sans-serif',
        'Courier New, Courier, monospace',
        'Georgia, serif',
        'Lucida Sans Unicode, Lucida Grande, sans-serif',
        'Tahoma, Geneva, sans-serif',
        'Times New Roman, Times, serif',
        'Trebuchet MS, Helvetica, sans-serif',
        'Verdana, Geneva, sans-serif'
      ],
    }

    configure :fontSize, {
      options: [
        'default',
        8,
        9,
        10,
        11,
        12,
        14,
        16,
        18,
        20,
        22,
        24,
        26,
        28,
        36,
        48,
        72
      ]
    }

    configure :heading, {
      options: [
        { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
        { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
        { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
        { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
        { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
        { model: 'heading5', view: 'h5', title: 'Heading 5', class: 'ck-heading_heading5' },
        { model: 'heading6', view: 'h6', title: 'Heading 6', class: 'ck-heading_heading6' },
        { model: 'formatted', view: 'pre', title: 'Formatted', class: 'ck-heading_formatted' },
        { model: 'address', view: 'address', title: 'Address', class: 'ck-heading_address' },
        { model: 'div', view: 'div', title: 'Normal (DIV)', class: 'ck-heading_div' }
      ]
    }

    configure :table, {
      contentToolbar: [
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        'tableProperties',
        'tableCellProperties',
        'toggleTableCaption'
      ]
    }

    configure :link, {
      decorators: {
        openInNewTab: {
            mode: 'manual',
            label: 'Open in a new tab',
            attributes: {
                target: '_blank',
                rel: 'noopener noreferrer'
            }
        }
      }
    }

  end

  presets.define :basic, inherit: false do
    version '43.3.0'
    license_key ENV["CKEDITOR_LICENSE_KEY"]
    toolbar :sourceEditing, :|, :cut, :copy, :|, :undo, :redo, :|,
            :findAndReplace, :selectAll, :|, :bold, :italic, :underline, :strikethrough,
            :subscript, :superscript, :removeFormat, :|, :bulletedList, :numberedList,
            :outdent, :indent, :blockQuote, :|, :alignment, :link, :anchor, :|,
            :insertTable, :horizontalLine, :|, :fontFamily, :fontSize, :heading, :|, :fontColor, :fontBackgroundColor, should_group_when_full: false

    plugins :Essentials, :Paragraph, :Heading, :Bold, :Italic, :Underline, :Strikethrough,
            :Subscript, :Superscript, :RemoveFormat, :FindAndReplace, :SelectAll, :Alignment,
            :List, :Indent, :BlockQuote, :Link, :Table, :TableToolbar, :TableCaption, :TableProperties,
            :TableCellProperties, :HorizontalLine, :Font, :FontFamily, :FontSize,
            :FontColor, :FontBackgroundColor, :SourceEditing, :Indent, :IndentBlock
    translations :de, :en, :es, :fr, :it, :ja, :nl, :pt, :zh

    configure :fontFamily, {
      options: [
        'default',
        'Arial, Helvetica, sans-serif',
        'Calibri',
        'Comic Sans MS, cursive, sans-serif',
        'Courier New, Courier, monospace',
        'Georgia, serif',
        'Lucida Sans Unicode, Lucida Grande, sans-serif',
        'Tahoma, Geneva, sans-serif',
        'Times New Roman, Times, serif',
        'Trebuchet MS, Helvetica, sans-serif',
        'Verdana, Geneva, sans-serif'
      ],
    }

    configure :fontSize, {
      options: [
        'default',
        8,
        9,
        10,
        11,
        12,
        14,
        16,
        18,
        20,
        22,
        24,
        26,
        28,
        36,
        48,
        72
      ]
    }

    configure :heading, {
      options: [
        { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
        { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
        { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
        { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
        { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
        { model: 'heading5', view: 'h5', title: 'Heading 5', class: 'ck-heading_heading5' },
        { model: 'heading6', view: 'h6', title: 'Heading 6', class: 'ck-heading_heading6' },
        { model: 'formatted', view: 'pre', title: 'Formatted', class: 'ck-heading_formatted' },
        { model: 'address', view: 'address', title: 'Address', class: 'ck-heading_address' },
        { model: 'div', view: 'div', title: 'Normal (DIV)', class: 'ck-heading_div' }
      ]
    }

    configure :table, {
      contentToolbar: [
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        'tableProperties',
        'tableCellProperties',
        'toggleTableCaption'
      ]
    }

    configure :link, {
      decorators: {
        openInNewTab: {
            mode: 'manual',
            label: 'Open in a new tab',
            attributes: {
                target: '_blank',
                rel: 'noopener noreferrer'
            }
        }
      }
    }

  end

  presets.define :ultrabasic, inherit: false do
    version '43.3.0'
    license_key ENV["CKEDITOR_LICENSE_KEY"]
    toolbar :sourceEditing, :|, :bold, :italic, :underline, :strikethrough,
            :subscript, :superscript, :removeFormat, :|, :bulletedList, :numberedList,
            :fontFamily, :fontSize, :|, :link, :anchor, :|,
            :fontColor, :fontBackgroundColor, should_group_when_full: false

    plugins :Essentials, :Paragraph, :Bold, :Italic, :Underline, :Strikethrough,
            :Subscript, :Superscript, :RemoveFormat, :List, :Link, :Font,
            :FontFamily, :FontSize, :FontColor, :FontBackgroundColor, :SourceEditing, :Essentials, :Paragraph

    translations :de, :en, :es, :fr, :it, :ja, :nl, :pt, :zh

    configure :fontFamily, {
      options: [
        'default',
        'Arial, Helvetica, sans-serif',
        'Calibri',
        'Comic Sans MS, cursive, sans-serif',
        'Courier New, Courier, monospace',
        'Georgia, serif',
        'Lucida Sans Unicode, Lucida Grande, sans-serif',
        'Tahoma, Geneva, sans-serif',
        'Times New Roman, Times, serif',
        'Trebuchet MS, Helvetica, sans-serif',
        'Verdana, Geneva, sans-serif'
      ],
    }

    configure :fontSize, {
      options: [
        'default',
        8,
        9,
        10,
        11,
        12,
        14,
        16,
        18,
        20,
        22,
        24,
        26,
        28,
        36,
        48,
        72
      ]
    }

    configure :link, {
      decorators: {
        openInNewTab: {
            mode: 'manual',
            label: 'Open in a new tab',
            attributes: {
                target: '_blank',
                rel: 'noopener noreferrer'
            }
        }
      }
    }
  end

  presets.define :book, inherit: false do
    version '43.3.0'
    license_key ENV["CKEDITOR_LICENSE_KEY"]
    toolbar :bold, :italic, :underline, :strikethrough, :removeFormat, :|,
            :bulletedList, :numberedList, :|, :fontFamily, :fontSize, :|,
            :alignment, :link, :anchor, :|, :fontColor, :fontBackgroundColor, should_group_when_full: false

    plugins :Essentials, :Paragraph, :Bold, :Italic, :Underline, :Strikethrough,
            :RemoveFormat, :List, :Link, :Font, :FontFamily, :FontSize,
            :FontColor, :FontBackgroundColor, :Alignment

    translations :de, :en, :es, :fr, :it, :ja, :nl, :pt, :zh

    configure :fontFamily, {
      options: [
        'default',
        'Arial, Helvetica, sans-serif',
        'Calibri',
        'Comic Sans MS, cursive, sans-serif',
        'Courier New, Courier, monospace',
        'Georgia, serif',
        'Lucida Sans Unicode, Lucida Grande, sans-serif',
        'Tahoma, Geneva, sans-serif',
        'Times New Roman, Times, serif',
        'Trebuchet MS, Helvetica, sans-serif',
        'Verdana, Geneva, sans-serif'
      ],
    }

    configure :fontSize, {
      options: [
        'default',
        8,
        9,
        10,
        11,
        12,
        14,
        16,
        18,
        20,
        22,
        24,
        26,
        28,
        36,
        48,
        72
      ]
    }

    configure :link, {
      decorators: {
        openInNewTab: {
            mode: 'manual',
            label: 'Open in a new tab',
            attributes: {
                target: '_blank',
                rel: 'noopener noreferrer'
            }
        }
      }
    }

  end

  presets.define :welcome, inherit: false do
    version '43.3.0'
    license_key ENV["CKEDITOR_LICENSE_KEY"]
    toolbar :undo, :redo, :|, :sourceEditing, :fontFamily, :fontSize, :heading, :|,
            :bold, :italic, :underline, :strikethrough, :removeFormat, :|,
            :fontColor, :fontBackgroundColor, :|, :alignment, :|,
            :link, :|, :bulletedList, :numberedList, :outdent, :indent,
            :blockQuote, :|, :insertImageViaUrl, :fileManager, :|, :mediaEmbed, :insertTable, :horizontalLine, should_group_when_full: false

    plugins :Essentials, :Paragraph, :Bold, :Italic, :Underline, :Strikethrough,
            :RemoveFormat, :Link, :List, :Indent, :BlockQuote, :ImageToolbar,
            :Font, :FontFamily, :FontSize, :FontColor, :FontBackgroundColor,
            :Alignment, :Table, :TableToolbar, :TableCaption, :TableProperties,
            :TableCellProperties , :LinkImage, :MediaEmbed, :Image, :ImageInsert,
            :ImageCaption, :ImageStyle, :ImageResize, :HorizontalLine, :SourceEditing,
            :Heading, :Indent, :IndentBlock

    plugin :FileManagerPlugin, window_name: :imageUpload
    plugin :CustomSimpleUploadAdapter, window_name: :simpleUploadAdapter

    plugins do
      remove(:Base64UploadAdapter)
    end

    configure :simpleUpload, {
      uploadUrl: '/ckeditor/pictures'
    }

    translations :de, :en, :es, :fr, :it, :ja, :nl, :pt, :zh

    configure :fontFamily, {
      options: [
        'default',
        'Arial, Helvetica, sans-serif',
        'Calibri',
        'Comic Sans MS, cursive, sans-serif',
        'Courier New, Courier, monospace',
        'Georgia, serif',
        'Lucida Sans Unicode, Lucida Grande, sans-serif',
        'Tahoma, Geneva, sans-serif',
        'Times New Roman, Times, serif',
        'Trebuchet MS, Helvetica, sans-serif',
        'Verdana, Geneva, sans-serif'
      ],
    }

    configure :fontSize, {
      options: [
        'default',
        8,
        9,
        10,
        11,
        12,
        14,
        16,
        18,
        20,
        22,
        24,
        26,
        28,
        36,
        48,
        72
      ]
    }

    configure :heading, {
      options: [
        { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
        { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
        { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
        { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
        { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
        { model: 'heading5', view: 'h5', title: 'Heading 5', class: 'ck-heading_heading5' },
        { model: 'heading6', view: 'h6', title: 'Heading 6', class: 'ck-heading_heading6' },
        { model: 'formatted', view: 'pre', title: 'Formatted', class: 'ck-heading_formatted' },
        { model: 'address', view: 'address', title: 'Address', class: 'ck-heading_address' },
        { model: 'div', view: 'div', title: 'Normal (DIV)', class: 'ck-heading_div' }
      ]
    }

    configure :link, {
      decorators: {
        openInNewTab: {
            mode: 'manual',
            label: 'Open in a new tab',
            attributes: {
                target: '_blank',
                rel: 'noopener noreferrer'
            }
        }
      }
    }


    configure :table, {
      contentToolbar: [
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        'tableProperties',
        'tableCellProperties',
        'toggleTableCaption'
      ]
    }

    configure :mediaEmbed, {
      previewsInData: true
    }

    configure :image, {
      toolbar: [
        'imageStyle:block',
        'imageStyle:side',
        '|',
        'imageStyle:alignLeft', 'imageStyle:alignRight',
        '|',
        'resizeImage',
        '|',
        'toggleImageCaption',
        'imageTextAlternative',
        '|',
        'linkImage'
      ]
    }

  end

end
```

The above is my ckeditor5.rb file code.

**Comment by dil-bparihar** [comment]
I am checking with 1.25.0. Take sometime to deploy and test.

**Comment by dil-bparihar** [comment]
ok @Mati365

**Comment by dil-bparihar** [comment]
@Mati365 I have checked and confirmed that it is breaking from `VERSION: 1.26.0` . For `VERSION 1.25.0` it is working fine.

**Comment by dil-bparihar** [comment]
> [@dil-bparihar](https://github.com/dil-bparihar) It looks like [patching](https://github.com/Mati365/ckeditor5-rails/compare/v1.25.0...v1.26.0) broke something. No idea what. I see that `version` helper which I added recently has option to disable automatic patching.
> 
> Consider adding `apply_patches: false` to your `version` call: `version '44.1.0', apply_patches: false`

This i already tried still it is breaking.

**Comment by dil-bparihar** [comment]
@Mati365  After upgraded to version: 1.28.0 it is working fine. BTW which version of ckeditor library i should use. Which one is the latest. Right now i have used `44.3.0` .

**Comment by dil-bparihar** [comment]
Even color picker is also working fine without patch. @Mati365

**Comment by Mati365** [comment]
@dil-bparihar I managed to fix that issue and merge it to upstream, so patch is no longer needed. I'm closing this issue as resolved.

**Comment by dil-bparihar** [comment]
@Mati365 Again the issue has arrived when used `custom_translations` in preset. I think the issue is in loading the plugin code which has await `import("ckeditor5");` or not sure what could be the main reason. Same i was getting earlier for simple_upload_adapter. But for that i removed the original your plugin and added my custom plugin.

Example code:

```ruby
plugin :CustomSimpleUploadAdapter, window_name: :simpleUploadAdapter

  plugins do
    remove(:Base64UploadAdapter)
  end

  configure :simpleUpload, {
    uploadUrl: '/ckeditor/pictures'
  }
```

================================================================

```javascript
import { Plugin, FileRepository } from 'ckeditor5';

window.simpleUploadAdapter = class CustomSimpleUploadAdapter extends Plugin {
  static get requires() {
    return [FileRepository];
  }

  static get pluginName() {
    return 'CustomSimpleUploadAdapter';
  }

  init() {
    const fileRepository = this.editor.plugins.get(FileRepository);
    const config = this.editor.config.get('simpleUpload');

    if (!config || !config.uploadUrl) {
      console.warn('Upload URL is not configured');
      return;
    }

    fileRepository.createUploadAdapter = (loader) => ({
      async upload() {
        try {
          const file = await loader.file;
          const formData = new FormData();
          formData.append('upload', file);

          return new Promise((resolve, reject) => {
            const xhr = new XMLHttpRequest();

            xhr.open('POST', config.uploadUrl, true);
            xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');

            // Add CSRF token from meta tag
            const csrfMeta = document.querySelector('meta[name="csrf-token"]');
            const csrfToken = csrfMeta ? csrfMeta.content : null;

            if (csrfToken) {
              xhr.setRequestHeader('X-CSRF-Token', csrfToken);
            }

            xhr.upload.onprogress = (evt) => {
              if (evt.lengthComputable) {
                loader.uploadTotal = evt.total;
                loader.uploaded = evt.loaded;
              }
            };

            xhr.onload = () => {
              if (xhr.status >= 200 && xhr.status < 300) {
                const data = JSON.parse(xhr.response);
                resolve({ default: data.url });
              } else {
                reject(`Upload failed: ${xhr.statusText}`);
              }
            };

            xhr.onerror = () => reject('Upload failed');
            xhr.onabort = () => reject('Upload aborted');

            xhr.send(formData);
            this._xhr = xhr;
          });
        } catch (error) {
          throw error;
        }
      },

      abort() {
        if (this._xhr) {
          this._xhr.abort();
        }
      }
    });
  }
}
```

Then i loaded it manually this file with:

`= javascript_include_tag "ckeditor_plugins/simple-upload-adapter.js", type: "module"`

So my question is i can do the same for this also but this is not a solution again if you add any new plugin or something again i will have to add it like this.

Is there any proper solution we can find ?

**Comment by Mati365** [comment]
@dil-bparihar Try bump to `1.28.1`, I added `type: module` to added inline scripts. Maybe it'll help.

**Comment by dil-bparihar** [comment]
> [@dil-bparihar](https://github.com/dil-bparihar) Try bump to `1.28.1`, I added `type: module` to added inline scripts. Maybe it'll help.

@Mati365 Its not working.

**Comment by dil-bparihar** [comment]
@Mati365 I have also checked the CPU utilisation and memory. Its getting high upto 95%. When the page is trying to load. The issue is while loading the script for cjs listener only. I am sure. The time i have added custom translation method in presets it script tag is trying to add and earlier with custom translation application works fine.

**Comment by Mati365** [comment]
@dil-bparihar You did not provide any stack-trace or information what is causing that CPU utilization. Please check the logs. JS code is not executed at the server side so there should be no difference if `await import` is used or not.

**Comment by dil-bparihar** [comment]
Issue is when ckeditor_assets load again on page refresh it breaks. If we refresh the page 15 times possibilities one time it could load @Mati365

**Comment by Mati365** [comment]
@dil-bparihar Is it the same bug or different one than you reported?

**Comment by dil-bparihar** [comment]
> [@dil-bparihar](https://github.com/dil-bparihar) Is it the same bug or different one than you reported?

same 504 error

**Comment by Mati365** [comment]
@dil-bparihar Do you have WAF enabled on your server?

**Comment by Mati365** [comment]
@dil-bparihar Is it crashing on non-prod servers?

**Comment by Mati365** [comment]
@dil-bparihar So dunno, you need to run profiler or something like that, that will trace which particular method fails. It looks like configuration error on your side.

**Comment by Mati365** [comment]
@dil-bparihar Can you check if your issue happens only when you use `ckeditor5_lazy_javascript_tags`? If you use normal `ckeditor5_assets` is it working fine?

**Comment by dil-bparihar** [comment]
> ckeditor5_lazy_javascript_tags

I am not using `ckeditor5_lazy_javascript_tags`. Issue is coming with `ckeditor5_assets` only @Mati365

**Comment by dil-bparihar** [comment]
If i will remove custom translation method from all presets again things will start working. Issue only comes when plugin loaded via cjs-listener. @Mati365

**Comment by Mati365** [comment]
@dil-bparihar Can you test if your website works when you copy & paste inline script content with exact format to your `<head` and then disable translations? I'd like to check if the format causes the issue, or some internal logic inside the gem.

**Comment by dil-bparihar** [comment]
@Mati365  I tried that too. Earlier i removed the plugin from presets. And added plugin with a different window variable name and plugin name. And i added the event listener method and plugin code inside it and put it in my assets js file with proper console logs. But that too was also not working. But one thing i want to highlight as i did earlier also. For my JS controller requests editor loads perfectly fine. Issue only comes for HTTP controller request. Where the page loads.

**Comment by dil-bparihar** [comment]
> [@Mati365](https://github.com/Mati365) I tried that too. Earlier i removed the plugin from presets. And added plugin with a different window variable name and plugin name. And i added the event listener method and plugin code inside it and put it in my assets js file with proper console logs. But that too was also not working. But one thing i want to highlight as i did earlier also. For my JS controller requests editor loads perfectly fine. Issue only comes for HTTP controller request. Where the page loads.

But i tried that for background color picker patch code not fir this translation one. @Mati365 Do you want me to do the same for this also.

**Comment by Mati365** [comment]
@dil-bparihar Please check by adding them manually, not using inline plugins. Just paste script_tag, to the `<head` and check if:

1. This fails (it should fail according to your report)

```js
window.addEventListener('ckeditor:request-cjs-plugin:MyCustomPlugin', () => { window['MyCustomPlugin'] = (async()=>{const{Plugin:i}=await import("ckeditor5");return class extends i{init(){console.info("MyCustomPlugin was initialized");window.__customPlugin=true}}})();; }, { once: true });
```

2. If this fails (I removed `await import` and added `import( .. ).then`. Maybe syntax matters.

```js
window.addEventListener('ckeditor:request-cjs-plugin:MyCustomPlugin', () => {
  window['MyCustomPlugin'] = (()=>{
    return import("ckeditor5").then(({Plugin}) => {
      return class extends Plugin {
        init(){
          console.info("MyCustomPlugin was initialized");
          window.__customPlugin = true
        }
      };
    });
  })();
}, { once: true });
```

Maybe name of CJS event is wrong - check if it works with different names, for example: `plugin-MyCustomPlugin` or something like that.

**Comment by Mati365** [comment]
@dil-bparihar Yes, I know. What I asked in a previous message is to check which permutation of JS snippet works in your environment. Try adding manually this script to your head as I said previously.

**Comment by dil-bparihar** [comment]
`window.addEventListener('ckeditor:request-cjs-plugin:MyCustomPlugin', () => { window['MyCustomPlugin'] = (async()=>{const{Plugin:i}=await import("ckeditor5");return class extends i{init(){console.info("MyCustomPlugin was initialized");window.__customPlugin=true}}})();; }, { once: true });`

`plugin :MyCustomPlugin, window_name: :MyCustomPlugin` Added in preset.

When i added the above code directly into the head inside script tag it works fine and even i tried adding the same way below code and it also works fine.

<img width="672" alt="Image" src="https://github.com/user-attachments/assets/81f0c7b9-3c21-4d3d-8e66-bdc3c7f13ee0" />

<img width="1054" alt="Image" src="https://github.com/user-attachments/assets/2f97eb21-b06e-4139-a9e3-d260929f4a42" />

@Mati365

**Comment by dil-bparihar** [comment]
But i am not sure why it is not working when added dynamically. @Mati365

**Comment by dil-bparihar** [comment]
Now again when i used the `simple_upload_adapter` in preset which is adding the cjs script tag dynamically for the plugin it is failing. Again i am getting same 504 gateway timeout error. @Mati365

**Comment by Mati365** [comment]
@dil-bparihar All of these plugins use inline plugins. Without proper profiling I cannot help you. Please run your application in production mode locally and check if this happen.

**Comment by dil-bparihar** [comment]
> [@dil-bparihar](https://github.com/dil-bparihar) All of these plugins use inline plugins. Without proper profiling I cannot help you. Please run your application in production mode locally and check if this happen.

Tried it is not failing on local with production mode also.

**Comment by dil-bparihar** [comment]
@Mati365  Is there a way if i add the custom_translation plugin code in head. How will i get the translations hash there ?

`static CUSTOM_TRANSLATIONS = Object.create( #{translations.to_json} );`

**Comment by Mati365** [comment]
@dil-bparihar Consider checking `1.82.3`, I reduced amount of `html_safe` calls.

**Comment by Mati365** [comment]
@dil-bparihar 

> Is there a way if i add the custom_translation plugin code in head. How will i get the translations hash there ?

That's why inline tags were used here. You need to interpolate translations to plugin, that injects translations to editor.

**Comment by dil-bparihar** [comment]
> [@dil-bparihar](https://github.com/dil-bparihar) Consider checking `1.82.3`, I reduced amount of `html_safe` calls.

This does not work @Mati365

**Comment by Mati365** [comment]
So don't know. Without proper stack trace or logs from your application, I'm not able to investigate this issue.

**Comment by dil-bparihar** [comment]
But @Mati365  I just worked forked your repository and commented the compress! method and used that gem and its working fine. which means the issue is in compressing the plugin.

<img width="572" alt="Image" src="https://github.com/user-attachments/assets/c2133bb9-8f04-42fb-bec7-d7489f8d519b" />

**Comment by Mati365** [comment]
@dil-bparihar Ok, now it's clear. So terser messes something in inline plugins. Maybe due to outdated dependencies or something. I'll add an option to disable compression of such plugins. Most likely today.

**Comment by dil-bparihar** [comment]
@Mati365 Please add an option also like compress: false for all the plugins together so that we should add this flag for each plugin. Thanks in advance.

**Comment by Mati365** [comment]
@dil-bparihar Option added, deployed. Please install `1.29.0` version. I adjusted docs. There should be additional `compress:` kwarg argument for `simple_upload_adapter`, `custom_translations` and other helpers that disables terser. Please let me know if it works.

**Comment by dil-bparihar** [comment]
@Mati365  Please also do something for strings not translated. I have already tried i18n method its not working. You can try at your end too for custom_translation. Issue already opened for that.
